### ISSUE TITLE
Configuration for rule "react/jsx-boolean-value" is invalid

### ISSUE THREAD

**Issue by Falkyouall** [zendesk/zopim-chat-web-sdk-sample-app#18]
Hi, i was trying to setup your project as described in the README.md, when i ran into following Error after running npm start

ERROR in ./src/index.js
Module build failed: Error: /Users/falk/git/node_modules/eslint-config-airbnb/rules/react.js:
	Configuration for rule "react/jsx-boolean-value" is invalid:
	Value "never,[object Object]" has more items than allowed.

Referenced from: airbnb
Referenced from: /Users/falk/git/.eslintrc.js
    at validateRuleOptions (/Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-validator.js:116:15)
    at /Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-validator.js:163:13
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-validator.js:162:35)
    at load (/Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-file.js:523:19)
    at /Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-file.js:392:36
    at Array.reduceRight (<anonymous>)
    at applyExtends (/Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-file.js:363:28)
    at load (/Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-file.js:530:22)
    at /Users/falk/git/chat-web-sdk-sample-app/node_modules/eslint/lib/config/config-file.js:392:36
 @ multi main
webpack: Failed to compile.

Everything is in place, node version is v9.4.0

**Comment by junyi** [comment]
Hi @Falkyouall,

First of all, apologies for the late response.

I ran `npm ls eslint-config-airbnb` in the project directory but don't see that it is being listed as one of the dependencies of the project.

From the logs you sent, it seems like the error is happening in a different directory under the folder `/Users/falk/git` instead of `/Users/falk/git/chat-web-sdk-sample-app`. Maybe you might want to check if you have additional `eslint` config added there?

> ERROR in ./src/index.js
Module build failed: Error: /Users/falk/git/node_modules/eslint-config-airbnb/rules/react.js:
Configuration for rule "react/jsx-boolean-value" is invalid:
Value "never,[object Object]" has more items than allowed.

Thanks,
Jun Yi
